_target_: src.model.ConformerModel
encoder_dim: 72
decoder_dim: 160
num_conform_blocks: 8
num_att_heads: 4
ker_size: 32
conv_expansion_factor: 2
freq: ${transforms.instance_transforms.train.get_spectrogram.n_mels}
